twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        categories: '@App\Repository\CategoryRepository'

when@test:
    twig:
        strict_variables: true

